// Reproducible first-party catalog, localized instructions and geometric SVG artwork.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const base = path.join(root, 'entry/src/main');
const games = [
 ['tictactoe','BOARD','井字棋','Three in a Row','三乘三棋盘，同屏双人连成三子。','Local two-player three-in-a-row.','双方轮流落下 × 和 ○，横、竖或斜线先连成三子获胜。棋盘填满仍无人连线则平局。','Take turns placing × and ○. Make a line of three horizontally, vertically or diagonally. A full board without a line is a draw.'],
 ['gomoku','BOARD','五子棋','Five in a Row','九路棋盘，双人自由五子连线。','Make five in a row on a 9×9 board.','同屏双人轮流落子，任意方向连续五子或以上获胜。本局采用自由规则，没有禁手。','Two local players take turns. Five or more consecutive pieces wins in any direction. Free placement rules; no forbidden moves.'],
 ['reversi','BOARD','翻转棋','Disc Reversal','夹住对方棋子，争夺棋盘多数。','Bracket opposing discs to capture them.','同屏双人对弈。落子必须在直线方向夹住对方棋子，夹住的全部翻为己方。无合法落点自动让行；双方均无法落子时，棋多者胜。小圆点表示合法位置。','Play locally with two players. Place a disc to bracket opponents along a straight line and flip them. A player with no move passes automatically. When neither can move, most discs wins. Dots mark legal moves.'],
 ['fourline','BOARD','落子四连','Falling Four','棋子落到底部，抢先连成四子。','Drop pieces and connect four.','同屏双人轮流点击一列，棋子落到该列最低空位。横、竖或斜线先连成四子获胜。','Two local players tap a column in turn. Pieces fall to the lowest empty slot. Connect four in any direction to win.'],
 ['nim','BOARD','取石子','Take the Stones','每次取一至三颗，拿走最后一颗获胜。','Take one to three; the last stone wins.','同屏双人轮流取走 1～3 颗石子，不能超过剩余数量。取走最后一颗的玩家获胜。难度改变初始石子数。','Two local players remove 1–3 stones per turn, up to the remaining count. Taking the last stone wins. Difficulty changes the starting pile.'],
 ['lights','PUZZLE','十字熄灯','Cross Lights','翻转相邻灯格，让棋盘全部熄灭。','Toggle a cross to turn all lights off.','点击格子，会同时翻转自身与上下左右相邻格子的亮灭状态。将所有暖黄色亮灯熄灭即可过关。谜题从全灭状态反向生成。','Tap a cell to toggle it and its four immediate neighbors. Turn off every warm yellow light. Every puzzle is generated from a solved board.'],
 ['flood','PUZZLE','色块归一','Region Fill','从左上角出发，用有限步数统一色块。','Unify the board from the top-left region.','选择下方数字颜色，将左上角相连的同色区域染成该颜色，并吸收相邻同色格。在步数上限内让所有格子相同。数字同时标识颜色。','Choose a numbered color to recolor the connected top-left region and absorb matching neighbors. Unify the board within the move limit. Numbers identify colors too.'],
 ['maze','PUZZLE','迷宫寻路','Maze Walk','探索随机迷宫，走到终点。','Find a path through a generated maze.','小机器人是当前位置，绿色拱门是出口，绿篱是墙。点击上下左右相邻的空地移动，也可使用方向按钮。到达出口即过关。每局迷宫保证连通。','The robot is you, the green arch is the exit, and hedges are walls. Tap an adjacent open cell or use the direction buttons. Reach the exit. Every generated maze is connected.'],
 ['hanoi','PUZZLE','汉诺塔','Tower Transfer','移动圆盘，完成三柱搬运。','Move a tower between three posts.','先点来源柱，再点目标柱，每次只能移动最上方最小的圆盘。小盘可放在大盘上，反之不可。将所有圆盘移至第 3 柱。数字越小盘越小。','Select a source post, then a destination. Only the top disc can move; larger discs cannot sit on smaller ones. Move every disc to post 3. Smaller numbers mean smaller discs.'],
 ['peg','PUZZLE','跳子独留','Last Peg','跳过相邻棋子，最终只留一颗。','Jump over pegs until only one remains.','先点棋子，再点同一直线上隔一格的空位。中间必须有棋子，被跳过的棋子会移除。最后只剩一颗即获胜；无路可跳则结束。关卡由合法逆向跳跃生成。','Select a peg, then an empty hole two cells away in a straight line. Jump over and remove the middle peg. Leave one peg to win. No legal jumps ends the game. Boards are generated with reverse legal moves.'],
 ['nonogram','PUZZLE','数字绘格','Run Grid','根据行列线索，填出格子图案。','Fill a grid using row and column runs.','行列线索描述连续实心格的组长，例如 2 1 表示连续两格、至少一格空白、再一格。点击切换填色。完成后点检查；任何满足全部线索的解都有效。','Clues give lengths of filled runs. For example, 2 1 means two filled cells, at least one gap, then one filled cell. Tap to toggle and check when ready. Any grid matching all clues is accepted.'],
 ['arithmetic','NUMBER','心算十题','Mental Arithmetic','加减乘十题练习，挑战心算准确率。','Ten questions of addition, subtraction and multiplication.','选择每道算式的正确答案，共 10 题。答对获得难度对应分数，答错不得分，完成后结算总分。','Choose the correct answer to each of ten questions. Correct answers earn points based on difficulty; wrong answers earn none.'],
 ['compare','NUMBER','算式比大小','Compare Expressions','算出两边大小，选择关系符号。','Compare the values of two expressions.','比较左右两个算式的结果，选择 ＜、＝ 或 ＞。共 10 题，按答对题数计分。','Compare the two expressions and choose <, = or >. Answer ten questions; correct answers earn points.'],
 ['sequence','NUMBER','数列推演','Number Patterns','找出规律，补上数列下一项。','Find the pattern and complete the sequence.','观察给出的数列并选择下一项。普通关卡为等差数列，困难可能出现翻倍数列。共 10 题，答对得分。','Choose the next term. Sequences use a constant difference; hard mode may also use doubling. Ten questions, scored for correct answers.'],
 ['binary','NUMBER','二进制解码','Binary Decoder','把二进制数字换算为十进制。','Convert binary numbers to decimal.','将带下标 ₂ 的二进制数转换成十进制，选择正确答案。共 10 题；难度越高，数字范围越大。','Convert the base-2 number to base 10 and select an answer. Ten questions. Higher difficulty increases the number range.'],
 ['targetsum','NUMBER','补数求和','Missing Addend','算出空缺数字，让总和成立。','Find the missing number in an addition.','已知总和及两个加数，选择问号处的数字，让等式成立。共 10 题，答对获得分数。','Given a sum and two addends, choose the missing addend. Ten questions; correct answers score points.'],
 ['schulte','MEMORY','数字寻序','Number Search','从一开始，按顺序找齐数字。','Find all numbers in ascending order.','从 1 开始依次点击数字，直到找到最后一个。点错不会跳过数字，但会增加步数。用更少的点击获得更高成绩。','Tap numbers in order from 1 to the last. Wrong taps count as moves but do not advance the target. Fewer taps earns a better score.'],
 ['memorysequence','MEMORY','顺序记忆','Sequence Recall','记住数字顺序，隐藏后依次复现。','Memorize and reproduce a digit sequence.','先观察数字序列，点「记好了」将其隐藏，然后按原顺序点击数字。重复数字也要重复点击；一次点错即结束。','Study the sequence, then tap Ready to hide it. Tap the digits in the same order, including repetitions. One incorrect tap ends the round.'],
 ['missing','MEMORY','记忆缺项','Missing Memory','记住一组数字，找出消失的那一个。','Remember a set and find the missing number.','记住显示的数字组，点「记好了」后会少一个数字。根据记忆选出消失的数字。共 10 题，答对计分。','Memorize the displayed set, then tap Ready. One number disappears. Choose the missing number from memory. Ten questions; correct answers earn points.'],
 ['reaction','REACTION','信号反应','Signal Tap','等待信号出现，测试点击反应。','Wait for the signal and test your response.','先点击开始，等待「现在点击」信号后再点。提前点会失败。完成后显示反应毫秒数；得分为 2000 减毫秒数，最低为 0。切后台或退出确认会取消当前计时，回到准备状态。','Tap to start and wait for the Tap now signal. Tapping early fails. Your response time is shown in milliseconds; score is 2000 minus that time, minimum zero. Backgrounding or opening exit confirmation resets the timing trial.']
];
const extras = {
 collection_art_robot:['小机器人，当前位置','Robot, your position'],collection_art_exit:['出口拱门','Exit arch'],collection_art_wall:['绿篱墙','Hedge wall'],collection_art_path:['小径','Path'],
 collection_art_player:['玩家 %d 的棋子','Player %d piece'],collection_art_on:['灯亮着','Light on'],collection_art_off:['灯已熄灭','Light off'],collection_art_filled:['已填色','Filled'],collection_art_peg:['棋子','Peg'],collection_art_legal:['可落子','Legal move'],
 collection_art_hidden:['已隐藏的记忆卡','Hidden memory card'],collection_art_card:['记忆卡 %d','Memory card %d'],collection_art_tower:['第 %d 柱，从上到下的圆盘：%s','Post %d, discs from top to bottom: %s'],
 module_desc:['玩趣盒 - 六大分类，33 款离线小游戏','LittleGames - 33 offline games across six categories'],
 app_splash_subtitle:['33 款小游戏，随手开一局。','33 mini-games. Pick one and play.'],
 settings_about_tagline:['六大分类，33 款小游戏','33 little games across six categories'],
 collection_correct:['上一题答对了 · 答案 %s','Previous answer correct · %s'],collection_wrong:['上一题正确答案：%s','Previous correct answer: %s'],
 cat_classic:['街机休闲','Arcade'],cat_puzzle:['逻辑解谜','Logic'],cat_board:['棋盘对弈','Board'],cat_number:['数字训练','Numbers'],cat_memory:['记忆专注','Focus'],cat_reaction:['反应节奏','Reaction'],
 collection_score:['挑战分','Challenge points'],collection_rules:['玩法说明','How to play'],collection_ready:['记好了','Ready'],collection_check:['检查答案','Check grid'],collection_check_again:['线索尚未全部满足，请继续调整。','Some clues do not match yet. Keep adjusting.'],collection_turn:['同屏双人 · 玩家 %d 回合','Local two-player · Player %d to move'],collection_steps:['已用 %d 步','Moves: %d'],collection_round:['第 %d / 10 题 · 得分 %d','Question %d / 10 · Score %d'],collection_player_win:['玩家 %d 获胜','Player %d wins'],collection_draw:['平局','Draw'],collection_win:['挑战完成','Challenge complete'],collection_fail:['本局结束','Round over'],collection_score_result:['本局得分：%d','Round score: %d'],collection_reaction_result:['反应时间：%d 毫秒','Response: %d ms'],collection_reaction_start:['点击开始','Tap to start'],collection_reaction_wait:['等待信号…','Wait for the signal…'],collection_reaction_go:['现在点击！','Tap now!'],collection_target:['下一个：%d','Next: %d'],collection_limit:['步数 %d / %d','Moves %d / %d'],collection_progress:['已复现 %d / %d','Recalled %d / %d'],collection_stones:['剩余 %d 颗石子','Stones remaining: %d'],collection_rows:['行线索（自上而下）','Row clues (top to bottom)'],collection_columns:['列线索（自左向右）','Column clues (left to right)'],collection_post:['第 %d 柱','Post %d'],collection_empty:['空','Empty'],collection_cell:['第 %d 行，第 %d 列：%s','Row %d, column %d: %s'],collection_count:['%d 款游戏','%d games'],collection_new:['新玩法 · 换个挑战','New games · Try something different'],collection_duel_score:['完成对局','Completed rounds']
};
for (const locale of ['base','zh_CN','en_US']) {
 const file=path.join(base,'resources',locale,'element/string.json'); const data=JSON.parse(fs.readFileSync(file,'utf8')); const en=locale==='en_US';
 const values={}; for(const [key,pair] of Object.entries(extras)) values[key]=pair[en?1:0];
 for(const g of games) { values[`game_${g[0]}_name`]=g[en?3:2];values[`game_${g[0]}_desc`]=g[en?5:4];values[`game_${g[0]}_rules`]=g[en?7:6]; }
 for(const [name,value] of Object.entries(values)) { const item=data.string.find(x=>x.name===name);if(item)item.value=value;else data.string.push({name,value}); }
 fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');
}
const catalog=`import { GameCategory, GameInfo } from '../common/GameConstants';\n\n/** Catalog for independently implemented collection games. */\nexport function collectionGames(): GameInfo[] {\n  return [\n${games.map(g=>`    { id: '${g[0]}', name: $r('app.string.game_${g[0]}_name'), category: GameCategory.${g[1]},\n      icon: $r('app.media.game_${g[0]}'), description: $r('app.string.game_${g[0]}_desc'),\n      highScore: 0, playCount: 0, scoreLabel: $r('app.string.${g[1]==='BOARD'?'collection_duel_score':'collection_score'}') }`).join(',\n')}\n  ];\n}\n\nexport function collectionRules(id: string): Resource {\n${games.map(g=>`  if (id === '${g[0]}') { return $r('app.string.game_${g[0]}_rules'); }`).join('\n')}\n  return $r('app.string.collection_rules');\n}\n`;
fs.writeFileSync(path.join(base,'ets/model/CollectionCatalog.ets'),catalog);
// The dedicated art generator owns icons and in-game materials together.
require('./generate-collection-art.cjs');
console.log('Generated 20 catalog entries and resources in all three locales.');
